import { appSchema, tableSchema } from "@nozbe/watermelondb";

const schema = appSchema({
  version: 7,
  tables: [
    tableSchema({
      name: "exercises",
      columns: [
        { name: "name", type: "string" },
        { name: "name_en", type: "string", isOptional: true },
        { name: "category", type: "string", isIndexed: true },
        { name: "primary_muscles", type: "string" },
        { name: "secondary_muscles", type: "string", isOptional: true },
        { name: "equipment", type: "string" },
        { name: "tracking_type", type: "string" },
        { name: "unit_preference", type: "string", isOptional: true },
        { name: "is_custom", type: "boolean" },
        { name: "is_archived", type: "boolean" },
        { name: "notes", type: "string", isOptional: true },
        { name: "sort_order", type: "number" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "plans",
      columns: [
        { name: "name", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "goal", type: "string", isOptional: true },
        { name: "is_active", type: "boolean" },
        { name: "is_archived", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "plan_days",
      columns: [
        { name: "plan_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "sort_order", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "plan_exercises",
      columns: [
        { name: "day_id", type: "string", isIndexed: true },
        { name: "exercise_id", type: "string", isIndexed: true },
        { name: "target_sets", type: "number" },
        { name: "target_reps", type: "string", isOptional: true },
        { name: "target_weight", type: "number", isOptional: true },
        { name: "rest_seconds", type: "number", isOptional: true },
        { name: "superset_group", type: "number", isOptional: true },
        { name: "sort_order", type: "number" },
        { name: "notes", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "workouts",
      columns: [
        { name: "plan_day_id", type: "string", isIndexed: true, isOptional: true },
        { name: "started_at", type: "number", isIndexed: true },
        { name: "finished_at", type: "number", isOptional: true },
        { name: "duration_seconds", type: "number" },
        { name: "total_volume", type: "number" },
        { name: "total_sets", type: "number" },
        { name: "rating", type: "number", isOptional: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "workout_exercises",
      columns: [
        { name: "workout_id", type: "string", isIndexed: true },
        { name: "exercise_id", type: "string", isIndexed: true },
        { name: "sort_order", type: "number" },
        { name: "volume", type: "number" },
        { name: "notes", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "workout_sets",
      columns: [
        { name: "workout_exercise_id", type: "string", isIndexed: true },
        { name: "set_number", type: "number" },
        { name: "weight", type: "number", isOptional: true },
        { name: "reps", type: "number", isOptional: true },
        { name: "duration_seconds", type: "number", isOptional: true },
        { name: "distance", type: "number", isOptional: true },
        { name: "rpe", type: "number", isOptional: true },
        { name: "is_warmup", type: "boolean" },
        { name: "is_completed", type: "boolean" },
        { name: "rest_seconds", type: "number", isOptional: true },
        { name: "is_pr", type: "boolean" },
        { name: "unit", type: "string" },
        { name: "completed_at", type: "number", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "personal_records",
      columns: [
        { name: "exercise_id", type: "string", isIndexed: true },
        { name: "pr_type", type: "string", isIndexed: true },
        { name: "value", type: "number" },
        { name: "workout_set_id", type: "string", isIndexed: true },
        { name: "achieved_at", type: "number", isIndexed: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "templates",
      columns: [
        { name: "name", type: "string" },
        { name: "description", type: "string", isOptional: true },
        { name: "goal", type: "string", isOptional: true },
        { name: "source_plan_id", type: "string", isOptional: true },
        { name: "is_built_in", type: "boolean" },
        { name: "is_archived", type: "boolean" },
        { name: "created_at", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "template_days",
      columns: [
        { name: "template_id", type: "string", isIndexed: true },
        { name: "name", type: "string" },
        { name: "sort_order", type: "number" },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "template_exercises",
      columns: [
        { name: "template_day_id", type: "string", isIndexed: true },
        { name: "exercise_id", type: "string", isIndexed: true },
        { name: "target_sets", type: "number" },
        { name: "target_reps", type: "string", isOptional: true },
        { name: "target_weight", type: "number", isOptional: true },
        { name: "rest_seconds", type: "number", isOptional: true },
        { name: "superset_group", type: "number", isOptional: true },
        { name: "sort_order", type: "number" },
        { name: "notes", type: "string", isOptional: true },
        { name: "updated_at", type: "number" },
      ],
    }),
    tableSchema({
      name: "sync_queue",
      columns: [
        { name: "table_name", type: "string", isIndexed: true },
        { name: "record_id", type: "string", isIndexed: true },
        { name: "action_type", type: "string", isIndexed: true },
        { name: "payload", type: "string" },
        { name: "created_at", type: "number", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "challenges",
      columns: [
        { name: "type", type: "string", isIndexed: true },
        { name: "target_value", type: "number" },
        { name: "current_value", type: "number" },
        { name: "start_date", type: "number", isIndexed: true },
        { name: "end_date", type: "number", isIndexed: true },
        { name: "is_completed", type: "boolean", isIndexed: true },
        { name: "created_at", type: "number", isIndexed: true },
        { name: "updated_at", type: "number", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "coach_clients",
      columns: [
        { name: "coach_id", type: "string", isIndexed: true },
        { name: "client_id", type: "string", isIndexed: true },
        { name: "status", type: "string", isIndexed: true },
        { name: "notes", type: "string", isOptional: true },
        { name: "created_at", type: "number", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "workout_comments",
      columns: [
        { name: "coach_id", type: "string", isIndexed: true },
        { name: "workout_id", type: "string", isIndexed: true },
        { name: "comment", type: "string" },
        { name: "created_at", type: "number", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "workout_videos",
      columns: [
        { name: "workout_set_id", type: "string", isIndexed: true },
        { name: "file_path", type: "string" },
        { name: "cloud_url", type: "string", isOptional: true },
        { name: "duration_seconds", type: "number" },
        { name: "file_size_bytes", type: "number" },
        { name: "created_at", type: "number", isIndexed: true },
      ],
    }),
  ],
});

export default schema;
